repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=100']
    - id: debug-statements
    - id: flake8
    - id: isort
      args: ['--profile', 'black']
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      args: ['--ignore-missing-imports']
    - id: mypy-strict
      args: ['--ignore-missing-imports', '--strict']
